services:
  db:
    image: postgres:alpine
    container_name: expense-db-container
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_PASSWORD}
    ports:
      - "${POSTGRES_PORT}:5432"
    volumes:
      - "postgres_data:/var/lib/postgressql/data"
    networks:
      - expense_network

volumes:
  postgres_data:

networks:
  expense_network:
    driver: bridge
    name: expense-network