basePath: /api
definitions:
  apperror.AppError:
    properties:
      code:
        type: integer
      message:
        type: string
    type: object
  appresponse.Meta:
    properties:
      paginate:
        $ref: '#/definitions/appresponse.Paginate'
      timestamp:
        type: string
    type: object
  appresponse.Paginate:
    properties:
      limit:
        type: integer
      next:
        type: string
      page:
        type: integer
      prev:
        type: string
      total_pages:
        type: integer
      total_rows:
        type: integer
    type: object
  appresponse.Response-any:
    properties:
      data: {}
      error:
        $ref: '#/definitions/apperror.AppError'
      message:
        type: string
      meta:
        $ref: '#/definitions/appresponse.Meta'
      success:
        type: boolean
    type: object
  dto.CreateDebtPayload:
    properties:
      amount:
        type: number
      due_date:
        example: "2006-01-02"
        type: string
      note:
        maxLength: 255
        type: string
      person_name:
        maxLength: 100
        minLength: 1
        type: string
      type:
        enum:
        - OWE
        - LENT
        type: string
    required:
    - amount
    - due_date
    - person_name
    - type
    type: object
  dto.CreateExpensePayload:
    properties:
      amount:
        type: number
      category_id:
        type: integer
      expense_date:
        example: "2006-01-02"
        type: string
      note:
        maxLength: 255
        type: string
      title:
        maxLength: 100
        minLength: 1
        type: string
    required:
    - amount
    - category_id
    - expense_date
    - title
    type: object
  dto.CreateIncomePayload:
    properties:
      amount:
        type: number
      category:
        maxLength: 100
        minLength: 1
        type: string
      income_date:
        example: "2006-01-02"
        type: string
      note:
        maxLength: 255
        type: string
      title:
        maxLength: 100
        minLength: 1
        type: string
    required:
    - amount
    - category
    - income_date
    - title
    type: object
  dto.UpdateDebtPayload:
    properties:
      amount:
        type: number
      due_date:
        example: "2006-01-02"
        type: string
      note:
        maxLength: 255
        type: string
      person_name:
        maxLength: 100
        minLength: 1
        type: string
      type:
        enum:
        - OWE
        - LENT
        type: string
    type: object
  dto.UpdateExpensePayload:
    properties:
      amount:
        type: number
      category_id:
        minimum: 1
        type: integer
      expense_date:
        example: "2006-01-02"
        type: string
      note:
        maxLength: 255
        type: string
      title:
        maxLength: 100
        minLength: 1
        type: string
    type: object
  dto.UpdateIncomePayload:
    properties:
      amount:
        type: number
      category:
        maxLength: 100
        minLength: 1
        type: string
      income_date:
        example: "2006-01-02"
        type: string
      note:
        maxLength: 255
        type: string
      title:
        maxLength: 100
        minLength: 1
        type: string
    type: object
info:
  contact: {}
  description: A lightweight backend RESTful API designed for tracking and managing
    personal or organizational expenses. This API provides secure endpoints to log
    daily expenses, categorize spending, and generate basic financial summaries.
  title: API Backend Expense
  version: "1.0"
paths:
  /debts:
    get:
      consumes:
      - application/json
      description: get all existing debt
      parameters:
      - description: Page
        in: query
        name: page
        type: integer
      - description: Limit
        in: query
        name: limit
        type: integer
      - description: Type (optional)
        in: query
        name: type
        type: integer
      - description: IsPaid (optional)
        in: query
        name: is_paid
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/appresponse.Response-any'
      summary: List debt
      tags:
      - debts
    post:
      consumes:
      - application/json
      description: create debt
      parameters:
      - description: Create new debt payload
        in: body
        name: request
        required: true
        schema:
          $ref: '#/definitions/dto.CreateDebtPayload'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/appresponse.Response-any'
      summary: Add new debt
      tags:
      - debts
  /debts/{id}:
    delete:
      consumes:
      - application/json
      description: delete debt
      parameters:
      - description: Debt ID
        in: path
        name: id
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/appresponse.Response-any'
      summary: Remove debt
      tags:
      - debts
    get:
      consumes:
      - application/json
      description: get one debt by id
      parameters:
      - description: Debt ID
        in: path
        name: id
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/appresponse.Response-any'
      summary: Get a debt
      tags:
      - debts
    put:
      consumes:
      - application/json
      description: update debt
      parameters:
      - description: Debt ID
        in: path
        name: id
        required: true
        type: integer
      - description: Edit debt payload
        in: body
        name: request
        required: true
        schema:
          $ref: '#/definitions/dto.UpdateDebtPayload'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/appresponse.Response-any'
      summary: Edit debt
      tags:
      - debts
  /debts/{id}/paid:
    patch:
      consumes:
      - application/json
      description: paid debt
      parameters:
      - description: Debt ID
        in: path
        name: id
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/appresponse.Response-any'
      summary: Change status debt as paid
      tags:
      - debts
  /expenses:
    get:
      consumes:
      - application/json
      description: get all existing expense
      parameters:
      - description: Page
        in: query
        name: page
        type: integer
      - description: Limit
        in: query
        name: limit
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/appresponse.Response-any'
      summary: List expense
      tags:
      - expenses
    post:
      consumes:
      - application/json
      description: create expense
      parameters:
      - description: Create new expense payload
        in: body
        name: request
        required: true
        schema:
          $ref: '#/definitions/dto.CreateExpensePayload'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/appresponse.Response-any'
      summary: Add new expense
      tags:
      - expenses
  /expenses/{id}:
    delete:
      consumes:
      - application/json
      description: delete expense
      parameters:
      - description: Income ID
        in: path
        name: id
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/appresponse.Response-any'
      summary: Remove expense
      tags:
      - expenses
    get:
      consumes:
      - application/json
      description: get one filters by expense id
      parameters:
      - description: Income ID (Optional)
        in: path
        name: id
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/appresponse.Response-any'
      summary: Get an expense
      tags:
      - expenses
    put:
      consumes:
      - application/json
      description: update expense
      parameters:
      - description: Income ID
        in: path
        name: id
        required: true
        type: integer
      - description: Edit expense payload
        in: body
        name: request
        required: true
        schema:
          $ref: '#/definitions/dto.UpdateExpensePayload'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/appresponse.Response-any'
      summary: Edit expense
      tags:
      - expenses
  /incomes:
    get:
      consumes:
      - application/json
      description: get all income
      parameters:
      - description: Page
        in: query
        name: page
        type: integer
      - description: Limit
        in: query
        name: limit
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/appresponse.Response-any'
      summary: List income
      tags:
      - incomes
    post:
      consumes:
      - application/json
      description: create income
      parameters:
      - description: Create new income payload
        in: body
        name: request
        required: true
        schema:
          $ref: '#/definitions/dto.CreateIncomePayload'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/appresponse.Response-any'
      summary: Add new income
      tags:
      - incomes
  /incomes/{id}:
    delete:
      consumes:
      - application/json
      description: delete income
      parameters:
      - description: Income ID
        in: path
        name: id
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/appresponse.Response-any'
      summary: Remove income
      tags:
      - incomes
    get:
      consumes:
      - application/json
      description: get one filters by income id
      parameters:
      - description: Income ID (Optional)
        in: query
        name: id
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/appresponse.Response-any'
      summary: Get an income
      tags:
      - incomes
    put:
      consumes:
      - application/json
      description: update income
      parameters:
      - description: Income ID
        in: path
        name: id
        required: true
        type: integer
      - description: Edit income payload
        in: body
        name: request
        required: true
        schema:
          $ref: '#/definitions/dto.UpdateIncomePayload'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/appresponse.Response-any'
      summary: Edit income
      tags:
      - incomes
swagger: "2.0"
